site_name: Livekit MCP Client
theme: readthedocs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: false
            show_category_heading: false
            show_if_no_docstring: true
            show_signature_annotations: true
            show_source: true
nav:
  - Home: index.md
  - API Reference: api.md
